---
# define pihole service
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    # lines deleted

    environment:
      WEBPASSWORD_FILE: pihole_webpasswd

    # lines deleted

    secrets:
      - pihole_webpasswd
    restart: unless-stopped

# define pihole_webpasswd secret
secrets:
  pihole_webpasswd:
    file: ./pihole_password.txt
...